Add All Graphs to Website
ronuma/legends pull request #90
Opened 2023-04-30 06:50 UTC by pridapablo

Modifications to the API were necessary. The endpoints modified were under the /stats/ route.

A new view was added to the database v3 creation script and has already been added to the production DB.

The text input is still not looking great on the website graph section, but all graphs are working and looking good (in carousel)

2023-04-30 06:53 UTC, pridapablo commented
@IksGarG en mi opinión no se ve nada mal.

Si quieres le das un poquito de estilo una vez que quede mergeada esta branch. (En mi opinión solo falta arreglar el text input field)

@ronuma edité API (ya quedó la documentación). Porfa deployea los cambios una vez que esto se pushé a main.

2023-05-01 00:43 UTC, ronuma requested changes
Lo de los constants creo que sí sería bueno. En lo de la tabla solo es para saber cuál es esa tabla de hero_sessions.

2023-05-01 00:43 UTC, ronuma commented on Web/back/quetzal-api/helpers/stats.js
> +const statLimits = {
No sería mejor esto ponerlo en el archivo constants?? No sé

2023-05-01 00:43 UTC, ronuma commented on Web/back/quetzal-api/helpers/stats.js
> +      `SELECT * FROM quetzal.hero_sessions WHERE email = '${email}' ORDER BY session_id`
Qué es esta tabla?

2023-05-01 02:23 UTC, pridapablo commented on Web/back/quetzal-api/helpers/stats.js
> +const statLimits = {
ahorita lo pongo ahí, es una muy buena idea

2023-05-01 02:23 UTC, pridapablo commented on Web/back/quetzal-api/helpers/stats.js
> +      `SELECT * FROM quetzal.hero_sessions WHERE email = '${email}' ORDER BY session_id`
es un nuevo view. Este pr integra el nuevo sql que la genera.

De nuevo, para no exponer la lógica de la base de datos en el API... Es un inner join de sessions y heroes

2023-05-01 02:25 UTC, pridapablo commented on Web/back/quetzal-api/helpers/stats.js
> +      `SELECT * FROM quetzal.hero_sessions WHERE email = '${email}' ORDER BY session_id`
Lo voy a volver a probar locar y te aviso cuando esto esté ready 2 merge

2023-05-02 18:18 UTC, IksGarG approved these changes
Ya deberia de jalar todo
>:3

2023-05-02 18:21 UTC, IksGarG approved these changes
Looks Great!

2023-05-02 18:21 UTC, merged